### ISSUE TITLE
Fix slash command handler to support both commands, subcommands, and subcommand groups

### ISSUE THREAD

**Issue by oof2win2** [FactorioAntigrief/FactorioAntigrief#172]
The clientside bot should be able to support commands, subcommand and subcommand, in a structure like this:
```
/ping - Command
/privatebans
	/privatebans create - Subcommand
	/privatebans remove - Subcommand
/config
	/config view - Subcommand
	/config linkedadmins - Subcommand group
		/config linkedadmins create - Subcommand
		/config linkedadmins remove - Subcommand
```
The function that needs to be edited is `executeCommandInteraction` in https://github.com/FactorioAntigrief/FactorioAntigrief/blob/master/apps/clientside-bot/src/base/Commands.ts#L56

**Comment by luckspt** [comment]
By this issue are you looking to use the `executeCommandInteraction` in all of the commands, instead of some commands calling it?

**Comment by oof2win2** [comment]
Nevermind, this is my bad. `CommandInteractionOptionResolver.getSubCommandGroup` (what is called in the [`executeCommandInteraction` function](https://github.com/FactorioAntigrief/FactorioAntigrief/blob/fff646a9b38a442819d73abddf35308cccc8fa18/apps/clientside-bot/src/base/Commands.ts#L57)) accepts a boolean of whether it should throw an error if it was not able to find the subcommand group name. I have put in `true` instead of `false`, as `false` would make it not throw errors and instead be null.
